-- 코드를 입력하세요
SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH, A.GENDER, COUNT(DISTINCT(B.USER_ID)) AS USERS
FROM ONLINE_SALE AS B LEFT JOIN USER_INFO AS A 
ON A.USER_ID = B.USER_ID	
WHERE A.GENDER IS NOT NULL 
GROUP BY YEAR, MONTH, A.GENDER
ORDER BY YEAR, MONTH, A.GENDER