-- 코드를 작성해주세요
select count(FISH_INFO.ID) as FISH_COUNT, FISH_NAME_INFO.FISH_NAME
from FISH_INFO left join FISH_NAME_INFO
on FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
group by FISH_NAME
order by FISH_COUNT DESC;
