-- 코드를 입력하세요
SELECT APPOINTMENT.APNT_NO, PATIENT.PT_NAME, APPOINTMENT.PT_NO, APPOINTMENT.MCDP_CD, DOCTOR.DR_NAME, APPOINTMENT.APNT_YMD
FROM APPOINTMENT 
    LEFT JOIN DOCTOR ON APPOINTMENT.MDDR_ID = DOCTOR.DR_ID
    LEFT JOIN PATIENT ON APPOINTMENT.PT_NO = PATIENT.PT_NO
WHERE APPOINTMENT.APNT_YMD LIKE "2022-04-13%" AND APPOINTMENT.APNT_CNCL_YN = "N" AND DOCTOR.MCDP_CD = "CS"
ORDER BY APPOINTMENT.APNT_YMD;